title: "Florian Emsmann"
description: "Hello, this is my data portfolio page"
logo: /assets/img/profile_picture.jpg
show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
