title: "Florian Emsmann"
description: [LinkedIn](www.linkedin.com/in/florianemsmann)
logo: /assets/img/profile_picture.jpg
# show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
