title: "Florian Emsmann"
# description: "An educational background in economic psychology, currently working in data management and motivated to dive deeper into data analytics and data science"
logo: /assets/img/profile_picture.jpg
# show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
