title: "Florian Emsmann"
description: "This is my data analytics and data science portfolio website"
logo: /assets/img/profile_picture.png

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
