title: "Florian Emsmann"
description: [<img src="https://img.icons8.com/ios-filled/50/000000/linkedin.png" width="30" height="30" alt="LinkedIn">](https://linkedin.com/in/florianemsmann)
logo: /assets/img/profile_picture.jpg
# show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
