title: "Florian Emsmann"
description: "40 years old and currently living in Karlsruhe, Germany"
logo: /assets/img/profile_picture.jpg
# show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
